ministryofjustice/hmpps-person-record

helm_deploy/values-prod.yaml
Default values are to alert on messages older than 30 minutes or a build up of over 100 messages
=> FIX: enable prometheus alerting on queues we are consuming from

src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/CourtCaseEventsListener.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/CourtCaseEventsListenerIntTest.kt
Almost 400 of the errors in the last 12 hours, so reverting this change as it doesn't seem to help
=> CPR-145 remove limit of max messages - does not solve the JPA problems

src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/config/AuthAwareTokenConverter.kt
This warning seems OK to suppress based on this search - everyone is doing it:
https://github.com/search?q=UNCHECKED_CAST+path%3A**%2FAuthAwareTokenConverter.kt+language%3AKotlin&type=code&ref=advsearch
It is the only warning we had, so it should be simple to spot if we introduce any new ones
=> FIX: suppress unchecked cast warning

.circleci/config.yml
There are too many alerts in the alerts channel for my liking - we do not need to know about dev and preprod releases.
I also wonder about moving the production release notifications into the general channel
=> FIX: only notify slack for production releases

src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/entity/PersonEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/model/Person.kt, src/main/resources/db/migration/V21__remove_redundant_field_from_person.sql
'most_recent_prisoner_number' is now redundant as all records with that field have a PNC
=> CPR-298 Remove most recent prisoner number

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml
If we have a serious problem, the numberOfMessagesOnQueue alert should fire anyway. This was firing when we were slowly processing large volumes of messages - we already knew we had a problem, but processing was actually working. The alert didn't tell us anything new.
=> CPR-307 set alerts for old messages back to the default of 30 minutes

src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/prison/PrisonDomainEventListenerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/test/messages/DomainEventMessages.kt
I think this is it - now the word `prisoner` actually refers to an individual in prison throughout our code
=> FIX: more prisoner to prison renaming

build.gradle.kts
Generates an HTML report showing test coverage. If we like this, we could get it published in the build, but it might be more useful to run locally. At the moment it runs after check (and seems quick) but it's not worth slowing the build down for
=> CPR-297 add a test coverage report

src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/client/model/ProbationCases.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/seeding/PopulateFromProbation.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/test/responses/AllProbationCasesResponses.kt
We are updating the probation-integration API to return Spring's PagedModel type, instead of the raw PageImpl type (see https://docs.spring.io/spring-data/commons/reference/repositories/core-extensions.html#core.web.page.paged-model).
This is technically a breaking change, however given this endpoint is only called on an ad hoc basis, it seemed simpler to just co-ordinate the API and client changes.
=> PI-2291 Update Probation Integration paged response model

src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/processors/hmcts/CourtCaseEventsProcessor.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/PersonService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/SearchService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/TelemetryService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/type/TelemetryEventType.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/config/MessagingMultiNodeTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/court/commonplatform/CommonPlatformCourtCaseListenerIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/court/libra/LibraCourtCaseListenerIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/prison/PrisonEventListenerIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/probation/ProbationEventListenerIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/SearchServiceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/test/RandomTestData.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/test/messages/CourtCommonPlatformMessages.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/test/responses/PrisonerSearchResponses.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/test/responses/ProbationCaseResponses.kt
Reverting all commits deployed to production today relating to Candidate Search to see if it fixes the CPU utilisation on the database
=> Cpr 215 revert

build.gradle.kts
I've created this so we don't have to upgrade opentelemetry at the same time  - we want to wait for the managed version of that to come in via the DPS gradle spring boot plugin
=> FIX: upgrade wiremock dependency

src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/repository/specifications/PersonSpecification.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/repository/specifications/queries/PersonSpecificationQueries.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/SearchServiceIntTest.kt
* Only does 1 join on the address table, rather than previously creating a join for each incoming postcode
=> CPR-215 Reduce joins on address table on queries

src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/repository/specifications/PersonSpecification.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/SearchServiceIntTest.kt
* This should resolve statements to 1<>1 "False" if the input values are null / not empty for postcode and dob. To ensure the statement resolves "mandatory" evaluations as expected
=> CPR-215 Tweak specification resolution

build.gradle.kts
I noticed we got an update for this test dependency and it looked unfamiliar - turns out we don't need it to make the tests pass
=> FIX: remove unused dependency

src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/client/model/sqs/domainevent/DomainEvent.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/config/MessagingMultiNodeTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/prison/PrisonEventListenerIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/probation/ProbationEventListenerIntTest.kt
Errors caused in DEV when messages fail to have `detailUrl`. As well as we don't use the property so might as well remove it.
=> CPR-388 Remove detail URL

README.md, build.gradle.kts
When a test fails in IntelliJ, there's not much point in running it 3 times.
=> FIX: only retry tests when CI env variable is set

src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/repository/specifications/PersonSpecification.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/court/libra/LibraCourtEventListenerIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/SearchServiceIntTest.kt
* Changed the JOINS to a `LEFT` join as if the searching row doesn't contain a child relationship it excludes the record out of the result as previously we did an INNER join on id and foreign key. For example if a record matches on first name, last name and dob. But the searching record also has a PNC but the existing one doesn't it would not return the result where we expect it would.
=> CPR-79 fix candidate search

src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/entity/PersonEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/repository/specifications/PersonSpecification.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/repository/specifications/queries/PersonSpecificationQueries.kt, src/main/resources/db/migration/V60__add_trigram_filtering.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/court/libra/LibraCourtEventListenerIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/SearchServiceIntTest.kt
* Use postgres https://www.postgresql.org/docs/current/pgtrgm.html trigram function to reduce the number of rows passed to the Levenshtein function. Includes indexes on the frequently used searched columns. Hopefully, speeding up the query / message processing.
=> CPR-453 Use postgres similarity to reduce number records on search

src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/repository/specifications/PersonSpecification.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/RetryExecutor.kt
* Shouldnt push to DLQ if next request succeeds from a 502. We only see a fraction of 502's (250 out of 250,000 requests)
=> CPR-453 retry on 502

src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/repository/specifications/PersonSpecification.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/repository/specifications/queries/PersonSpecificationQueries.kt, src/main/resources/db/migration/V60__add_postcode_index.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/SearchServiceIntTest.kt, src/test/resources/application-test.yml
Example resulting query:
```
select pe1_0.id,pe1_0.birth_country,pe1_0.birth_place,pe1_0.crn,pe1_0.currently_managed,pe1_0.date_of_birth,pe1_0.defendant_id,pe1_0.ethnicity,pe1_0.first_name,pe1_0.last_name,pe1_0.master_defendant_id,pe1_0.merged_to,pe1_0.middle_names,pe1_0.nationality,pe1_0.fk_person_key_id,pe1_0.prison_number,pe1_0.religion,pe1_0.self_match_score,pe1_0.sex,pe1_0.sexual_orientation,pe1_0.source_system,pe1_0.title,pe1_0.version 
from personrecordservice.person pe1_0 
left join personrecordservice.reference r1_0 
on pe1_0.id=r1_0.fk_person_id 
left join personrecordservice.address a1_0 
on pe1_0.id=a1_0.fk_person_id 
where 
(personrecordservice.soundex(pe1_0.first_name)=personrecordservice.soundex('twqnkwb') 
and personrecordservice.soundex(pe1_0.last_name)=personrecordservice …
```
=> CPR-453 remove levenshtein func from query

.circleci/config.yml
https://github.com/ministryofjustice/hmpps-circleci-orb/blob/main/release-notes/9.x.md
https://github.com/ministryofjustice/hmpps-circleci-orb/blob/main/release-notes/10.x.md
Nothing for us to worry about in the release notes
=> FIX: move time of daily security job to avoid clash and bump orb to v10

src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/person/ReclusterService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/type/TelemetryEventType.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/ReclusterServiceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/SearchServiceIntTest.kt
* Made results handle same for all results as extra complexity required to log certain scenarios with single/multiple clusters, which we can easily determine from the candidate record search event
=> CPR-438 Handle multiple results when reclustering

Makefile, docker-compose.yml
NB this renames the postgres container so if you already have them running, please run `docker compose down` first as the script relies on the container naming. I was struggling to run this when I had containers running from other projects.
Please pull this and check it works for you locally.
```mark.rees@MJ004359 hmpps-person-record % make start-containers
docker compose up -d
[+] Running 3/3
✔ Network hmpps-person-record_hmpps                             Created                                                                                                                                 0.0s 
✔ Container hmpps-person-record-postgres-hmpps-person-record-1  Started …
```
=> CPR-503 check whether containers are running before trying to start them

Makefile
it was just stopping the containers, then reporting that they were already running, even though they weren't. I tried to faff with make for a bit then went for the lazy option
=> FIX: make restart-containers was not working for me

.circleci/config.yml, Makefile
* https://docs.gradle.org/current/userguide/performance.html#increase_the_heap_size
* _JAVA_OPTIONS env var takes precedence in config hence overwriting orb default and not in properties file
* Should speed up build when re-trying test
=> CPR-79 Update JVM options for test

.circleci/config.yml, Makefile
* Use one gradle worker, as 4 causes test to error out on failure 
* One was default (increasing causes parallelisation) not suited for us yet.
=> CPR-79 Use one gradle worker

gradle/wrapper/gradle-wrapper.properties, gradlew
This reverts commit 1a984960500a2ec1468a7f55a69c3d46c0374169.
Temporarily until Kover can work with it
Top 2 merged PRs on 6 Jan actually fix this but we need to wait for a release so this will unblock us in the meantime
https://github.com/Kotlin/kotlinx-kover/pulls?q=is%3Apr+is%3Aclosed
=> Revert "Update dependency gradle to v8.12 (#764)"

src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/client/model/prisoner/CurrentlyManaged.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/prison/PrisonEventListenerIntTest.kt
Evidence for this change:
[References in our codebase](https://github.com/search?q=org%3Aministryofjustice+%22ACTIVE+IN%22&type=code)
[Prisoner Search Swagger](https://prisoner-search-dev.prison.service.justice.gov.uk/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config#/Popular/findByPrisonNumber)
[And more specifically](https://github.com/ministryofjustice/prison-api/blob/2de6f7399ea84801c051f834594cb5507666c2f5/src/main/java/uk/gov/justice/hmpps/prison/api/model/PrisonerSearchDetails.kt#L89) albeit from prisoner-api
=> CPR-537 fix all other statuses for currently managed

src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/RetryExecutor.kt
It's hard to tell from the stacktrace which error is being caught in here, so if we log it that should allow us to add it to the list of retryable entity exceptions
=> CPR-512 add a logging line to show the class of the uncaught exception

src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/court/commonplatform/CommonPlatformCourtEventListenerIntTest.kt
The blitzer functionality will come in handy when we finally get round to looking at the `row was updated by another transaction` errors - meanwhile this should hopefully prevent any random calls to person-match-score which make this test fail on my machine after a few `make test` runs
=> CPR-578 make blitzer test more reliable locally

src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/api/model/canonical/CanonicalAddress.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/controller/SearchIntTest.kt
CPR-508-address-fields-canonical add address fields to canonical api
=> CPR-508-address-fields-canonical

src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/api/model/canonical/CanonicalIdentifiers.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/api/model/canonical/CanonicalNationality.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/api/model/canonical/CanonicalRecord.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/api/model/canonical/Identifiers.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/controller/SearchIntTest.kt
"CPR-508-update-canonical-fields changed additionalidentifiers to identifiers and removed crn,cid,defendantId and prisonnumber from top level of the api"
=> CPR-508-update-canonical-fields

src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/config/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/config/MessagingMultiNodeTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/prison/PrisonEventListenerIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/probation/ProbationUnmergeEventListenerIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/seeding/UpdateFromProbationIntTest.kt
The simpler we can make stubbing, the easier the tests will be to understand.
I also think we should ideally not have any dependencies on wiremock outside the base classes
=> Tidy up wiremock

src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/repository/EventLogRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/config/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/ReclusterServiceIntTest.kt
https://github.com/ministryofjustice/hmpps-person-record/blob/a10a7a8909aa4039f2d37f15b0bd2db5c5171693/src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/message/recluster/ReclusterService.kt#L78
The theory is that `.first()` can be either record in the cluster although it is usually personC
An alternative fix would be to have the clusters be 3 records and 1 record and have 1 merge into the 3. Then `.first()` can only be one record
=> CPR-710 fix flaky test

helm_deploy/hmpps-person-record/templates/record-count-report-cron.yaml, helm_deploy/hmpps-person-record/values.yaml, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml
Runs report every hour (easier for initial testing)
=> CPR-622 Add cron job for report count

src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/config/SecurityConfiguration.kt
Uses this instead:
https://github.com/ministryofjustice/hmpps-kotlin-lib/blob/main/hmpps-kotlin-spring-boot-autoconfigure/src/main/kotlin/uk/gov/justice/hmpps/kotlin/auth/HmppsWebClientConfiguration.kt#L61
=> CPR-393 remove bean provided by kotlin-lib

src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/message/CreateUpdateService.kt
This should simply speed up processing as the delay between retries is shorted
=> CPR-640 retry db calls every 200ms

src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/api/controller/admin/ClustersController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/repository/PersonKeyRepository.kt
Would be better to order by lastModified but we don't currently have it so this is better than nothing
=> CPR-780 order clusters by ID so last page does not keep changing

src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/client/model/offender/ProbationCase.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/client/model/offender/ProbationCaseAlias.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/client/model/offender/ProbationCaseName.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/config/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/controller/canonical/CanonicalApiIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/controller/probation/ProbationApiIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/eventlog/EventLogServiceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/model/types/EthnicityCodeIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/model/types/NationalityCodeIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/model/types/SexCodeTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/model/types/TitleCodeIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/CreateUpdateServiceIntTest.kt
* Renamed as swagger evaluates the first `Name` object it finds as the docs so can have incorrect request payload examples with object of the same name
=> CPR-831 Rename Name data class for proper swagger documentation

src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/api/model/admin/AdminEventLogSummary.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/api/controller/admin/EventLogApiIntTest.kt
change dob and override marker to return null instead of string null
=> CPR-839-null-override
