- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/controller/PersonController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/controller/advice/PersonRecordControllerAdvice.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/entity/BaseAuditedEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/entity/PersonEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/repository/PersonRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/model/PersonDTO.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/PersonRecordService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/controller/PersonControllerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/model/PersonDTOTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/PersonRecordServiceTest.kt
- New create person POST controller endpoint
- Validation of parameters passed in and returning HTTP error response
- Addition of Location header with URL of newly created Person
-  Unit/Integration tests
> PIC-2913 Basic create person API

- src/main/resources/application-local.yml
- src/main/resources/application.yml
- src/main/resources/logback-spring.xml
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/controller/PersonControllerIntTest.kt
- src/test/resources/application-test.yml
- src/test/resources/logback.xml
- src/test/resources/sql/before-test.sql
- Enable person search integration tests
- Enable feign logging
- Refactor of integration tests
- Logging configuration tidy up
- Quieten down intellij JUnit logging output when running tests
> PIC-3159 Re-enable person search integration tests

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/entity/DeliusOffenderEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/entity/HmctsDefendantEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/repository/PersonRepositoryCustomImpl.kt
- src/main/resources/db/migration/V1__add_initial_tables.sql
- src/main/resources/logback-spring.xml
- src/test/resources/sql/before-test.sql
- Initial table structure for CPR defined in flyway script
- Fix integration test SQL script
- logging fix
> CPR-53 Flyway script for initial table structure

- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/OffenderServiceTest.kt
Just to check that I have the correct git setup
> Remove unused variable

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/CourtCaseEventsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/validate/PNCIdValidator.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/CourtCaseEventsServiceTest.kt
I was playing around with the CourtCaseService and this change seemed small and a slight improvement
> REFACTOR: simplify dependencies of CourtCaseService

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/validate/PNCIdValidator.kt
What are your thoughts on this style? 
I am not a Kotlin expert :-)
> REFACTOR: simplify event telemetry in validator

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/CourtCaseEventsListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/OffenderDomainEventsListener.kt
See https://mojdt.slack.com/archives/C69NWE339/p1705940591744919?thread_ts=1705940178.743949&cid=C69NWE339
> FIX: add operationId to all customEvents

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/CourtCaseEventsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/CourtCaseEventsListenerIntTest.kt
A simple approach to solving this problem for now. I will have a go at a refactor to see if we can prevent this for ever happening again
> CPR-162 fix

- .circleci/config.yml
ref: https://github.com/ministryofjustice/hmpps-circleci-orb/blob/main/release-notes/8.x.md
https://github.com/ministryofjustice/prison-offender-events/blob/a673c34f852113511ebd14a747f3d7c97d14a4cf/.circleci/config.yml#L54
> FIX: update circleci orb to v8 and add associated JIRA config

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/client/PrisonServiceClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/client/model/PhoneNumber.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/client/model/offender/ContactDetails.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/client/model/prisoner/Address.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/client/model/prisoner/Identifier.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/client/model/prisoner/Prisoner.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/client/model/prisoner/PrisonerDetails.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/entity/ContactEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/entity/PrisonerEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/PersonRecordService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/PrisonerService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/type/TelemetryEventType.kt
- src/main/resources/db/migration/V10__additional_prisoner_fields.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/CourtCaseEventsListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/PrisonerServiceTest.kt
- src/test/resources/__files/prisoner-details/GET_prisoner_addresses_success_any_prisoner_number.json
- src/test/resources/__files/prisoner-details/GET_prisoner_details_success_any_prisoner_number.json
- src/test/resources/mappings/prisoner-details/GET_prisoner_addresses_any_prisoner_number.json
- src/test/resources/mappings/prisoner-details/GET_prisoner_details_any_prisoner_number.json
Added end point to get prisoner addresses.
Refactored prisoner service to use prisoner details.
Updated IT.
> CPR-131 Nomis additional fields.

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/OffenderService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/PrisonerService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/RetryExecutor.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/type/TelemetryEventType.kt
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/OffenderServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/PrisonerServiceTest.kt
- src/test/resources/application-test.yml
Updated prisoner/offender services to use the retry mechanism for remote API calls.
> CPR-167 Added retry executor function

- src/test/resources/logback-test.xml
Before: (see `gradle build` step)
https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-person-record/1122/workflows/be1368c7-4cb5-469c-a58e-0de07335f65e/jobs/3343
After:
https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-person-record/1127/workflows/0177f9d6-3231-4b47-81a9-50dd17878e87/jobs/3355
> CPR-199 quieter test logging

- README.md
* Update README to remove redundant prerequisite
> CPR-XXX Update README

- helm_deploy/values-dev.yaml
- helm_deploy/values-prod.yaml
* Enable delius listeners in prod
> CPR-248 Enable delius listeners

- build.gradle.kts
https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-person-record/1307/workflows/f11e8201-3559-4cbf-91af-ba055574016b/jobs/3865
Fixes this
> FIX: pin bouncycastle version to fix CVEs

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/repository/specifications/PersonSpecification.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/PersonService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/court/libra/LibraCourtCaseListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/PersonServiceIntTest.kt
* Add missed AC: `AND originate from the same SourceSystemName as the newly received Person record`
> CPR-321 Actually search with source system

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/client/model/prisoner/Identifier.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/client/model/prisoner/PhysicalAttributes.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/processors/prison/PrisonEventProcessor.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/prison/PrisonEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/prison/PrisonEventListenerTest.kt
This reverts commit 21ccf68630634105b133a0494fd92811572262c7.
> Revert "CPR-353 correct prison retry configuration (#444)"

- detekt.yml
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/repository/specifications/PersonSpecification.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/SearchServiceIntTest.kt
* I'll update confluence page once / if merged
> CPR-215 Lower levenshtein score for postcode

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/processors/court/CourtEventProcessor.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/processors/prison/PrisonEventProcessor.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/processors/probation/ProbationEventProcessor.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/type/TelemetryEventType.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/court/commonplatform/CommonPlatformCourtEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/court/libra/LibraCourtEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/prison/PrisonEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/probation/ProbationEventListenerIntTest.kt
Removed court specific message and added them into general message received
> CPR-312-appinsight-message-received

- src/main/resources/db/migration/V36__add_indexes_for_person_identifier.sql
> CPR-312-adding-index

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/entity/AddressEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/entity/AliasEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/entity/ContactEntity.kt
removed cascade.all tag from child entities
> CPR-92-remove-cascade-all-from-child

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/entity/PersonEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/entity/ReferenceEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/model/types/IdentifierType.kt
- src/main/resources/db/migration/V42__add_references_table.sql
* Add initial reference table, adding mapping in subsequent PR's
> CPR-376 Add reference table

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/client/model/prisoner/Prisoner.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/prison/PrisonEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/test/responses/PrisonerSearchResponses.kt
update nationality and religion to be nullable
> CPR-349-fix-characteristics-mapping

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/PersonService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/ReadWriteLockService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/SearchService.kt
This reverts commit d776b36037c48ddeb9fbb19991568a02d55ab536.
> Revert "CPR-453 Make write locks more specific (#620)"

- src/main/resources/db/migration/V61__add_merged_to_index.sql
> CPR-460-add-index-merged-to

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/client/model/sqs/domainevent/AdditionalInformation.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/probation/ProbationMergeEventListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/processors/probation/ProbationUnmergeEventProcessor.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/config/MessagingMultiNodeTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/probation/ProbationUnmergeEventListenerIntTest.kt
add feign exception to merge/unmerge listeners
> CPR-459-merge-event-listener

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/repository/PersonBlockingRulesRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/SearchService.kt
added paging to hopefully resolve memory isue
> CPR-472-add-paging

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/repository/PersonKeyRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/repository/PersonRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/processors/probation/ProbationDeleteProcessor.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/person/DeletionService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/type/TelemetryEventType.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/config/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/court/libra/LibraCourtEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/prison/PrisonMergeEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/probation/ProbationDeleteListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/probation/ProbationEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/probation/ProbationMergeEventListenerIntTest.kt
Context of deletion flow:
https://app.diagrams.net/#G1kEDjYbXSXOjBAHsuPQdxA92rZRLnqgmF#%7B%22pageId%22%3A%22-Ab_2iY_B0UAYZNQ2W_j%22%7D
> CPR-445 Process Deletions

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/person/DeletionService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/person/ReclusterService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/search/MatchService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/config/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/config/MessagingMultiNodeTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/MatchServiceIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/ReclusterServiceIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/SearchServiceIntTest.kt
* Tests will be done as part of CPR-452
> CPR-439 initial multiple record in cluster, reclustering

- src/main/resources/logback-spring.xml
* Add console appenders, based of template repository. 
* As no console logs are written currently so not visible during (kubectl logs)
> CPR-498 Add console appenders

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jobs/GenerateTermFrequencies.kt
* Should resolve memory issue for term frequency
> CPR-79 Delete in batch

- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/config/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/config/MessagingMultiNodeTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/jobs/GenerateTermFrequenciesIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/prison/PrisonEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/prison/PrisonMergeEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/probation/ProbationDeleteListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/probation/ProbationEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/probation/ProbationMergeEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/probation/ProbationUnmergeEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/seeding/PopulateFromPrisonIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/seeding/PopulateFromProbationIntTest.kt
> Test tidy up

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/processors/cpr/ReclusterEventProcessor.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/message/ReclusterService.kt
https://docs.spring.io/spring-framework/reference/data-access/transaction/declarative/annotations.html#transaction-declarative-annotations-method-visibility
> FIX: transactional annotations do not work on private methods

- build.gradle.kts
https://docs.gradle.org/current/userguide/performance.html#optimize_the_compiler
> FIX: try to speed up compilation

- src/main/resources/db/migration/V71__update_person_aggregate_materialized_view.sql
* Turns out filtering of postcode length was done in wrong place, now effective after regex replace of whitespace.
* works in preprod
* works in prod
> CPR-510 update person aggregate data view (3rd Attempt)

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/processors/cpr/ReclusterEventProcessor.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/seeding/PopulateFromPrison.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/seeding/PopulateFromProbation.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/seeding/UpdateFromProbation.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/RetryExecutor.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/format/EncodingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/message/DeletionService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/message/MergeService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/message/TransactionalProcessor.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/message/UnmergeService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/search/MatchService.kt
refactory retry method to seperate http retries and entity retries
> CPR-512-refactor-retry

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/processors/cpr/ReclusterEventProcessor.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/seeding/PopulateFromPrison.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/seeding/PopulateFromProbation.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/seeding/UpdateFromProbation.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/RetryExecutor.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/format/EncodingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/message/DeletionService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/message/MergeService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/message/TransactionalProcessor.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/message/UnmergeService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/search/MatchService.kt
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/seeding/PopulateFromPrisonIntTest.kt
Try HTTP calls 3 times and DB calls 5 times. This was already happening but config was spread out
> CPR-512 simplify retry numbers

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/entity/PersonEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/seeding/PopulateFromPrison.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/seeding/PopulateFromProbation.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/seeding/UpdateFromProbation.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/person/PersonService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/config/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/court/libra/LibraCourtEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/MatchServiceIntTest.kt
refactor from method and update method in person entity
> CPR-566-rename-person-from

- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/SearchServiceIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/test/RandomTestData.kt
source: https://www.confused.com/car-insurance/guides/how-to-check-your-driving-licence
> CPR-566 more realistic driving license number

- helm_deploy/hmpps-person-record/values.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
pause messaging
alter readiness
> CPR-566-pause-messages

- helm_deploy/hmpps-person-record/values.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
This reverts commit 6a305b2f82ed759acb02b69b955c7a80c98d1f0b.
> Revert "CPR-566-pause-messages (#801)"

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/client/model/court/event/LibraHearingEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/entity/PersonEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/repository/PersonRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/repository/queries/BlockingRules.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/processors/court/CourtEventProcessor.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/model/person/Person.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/TelemetryService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/search/SearchService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/court/libra/LibraCourtEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/test/RandomTestData.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/test/messages/CourtLibraMessages.kt
> CPR-581-add-c-id

- src/main/resources/db/migration/V78__index_timestamp.sql
> CPR-605-index-timezone

- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/config/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/config/MessagingMultiNodeTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/controller/HealthCheckIntTest.kt
In case we ever decide to use something other than wiremock for stubbing....
> Cpr 582 wiremock

- src/main/resources/db/migration/V82__add_additional_address_fields.sql
CPR-508-add-additional-address-fields create new db script for address fields
> CPR-508-add-additional-address-fields

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/client/PersonMatchClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/client/model/match/PersonMatchScore.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/search/PersonMatchService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/search/SearchService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/config/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/config/MessagingMultiNodeTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/controller/HealthCheckIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/court/commonplatform/CommonPlatformCourtEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/court/libra/LibraCourtEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/cpr/ReclusterEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/prison/PrisonEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/probation/ProbationEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/probation/ProbationUnmergeEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/seeding/PopulateFromPrisonIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/seeding/PopulateFromProbationIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/seeding/PopulatePersonMatchIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/seeding/UpdateFromProbationIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/SearchServiceIntTest.kt
Reverts ministryofjustice/hmpps-person-record#863
> CPR-584 invoke person match

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/api/model/canonical/CanonicalRecord.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/controller/SearchIntTest.kt
CPR-508-uuid-name-change change name from personUUID to cprUUID
> CPR-508-uuid-name-change

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/api/model/canonical/CanonicalAddress.kt
> CPR-632-additional-work-canonical

- src/main/resources/application.yml
All requests to dev are currently returning 401 because this is not configured correctly
> CPR-634 correct URL for jwk

- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/config/MessagingMultiNodeTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/court/commonplatform/CommonPlatformCourtEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/court/libra/LibraCourtEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/prison/PrisonEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/prison/PrisonMergeEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/probation/ProbationEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/probation/ProbationMergeEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/probation/ProbationUnmergeEventListenerIntTest.kt
This will verify that every wiremock stub we set up is actually called.
Hopefully this will lead to a clearer understanding of how the application behaves, and exactly what the tests are covering.
It looks worse than it is - mostly it is adding nested classes
> Fix wiremock verification

- helm_deploy/values-prod.yaml
* Attempt number (i don't know any more).
* Improved response times on scoring ~ <1sec on preprod. [graph](https://portal.azure.com#@747381f4-e81f-4a43-bf68-ced6a1e14edf/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2Fa5ddf257-3b21-4ba9-a28c-ab30f751b383%2FresourceGroups%2Fnomisapi-preprod-rg%2Fproviders%2FMicrosoft.OperationalInsights%2Fworkspaces%2Fnomisapi-preprod/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA3WQTU7DQAxG95zCZDOplApxgCwqQF1BK9oLOImbGZT5qT1JKeLwTFKoUKUs%252FX1vPNZbhfBOx54kyt03nDQxwSplvqM3tARlCbnSNgRZBmLxbmkx1lotrvSE3Zeg1i97eNCEXdTqpq29i2icQCYnbFvibBY44GDSNA%252F4QA6DmQc%252BfCW3bQnZdJ5xBz%252FXjTl9RnINNEZCh%252BeLAahRKP%252BzobabXYIvMlQB2RMTRoLtFGQp2NWer%252FPoSXprkc0XAQ7E2NKv8b2Z1uPQ5s89YzTevcoCqvP%252F%252Fwuo …
> CPR-629 Turn on scoring again

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/client/model/sqs/SQSMessage.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/processors/court/CourtEventProcessor.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/config/MessagingMultiNodeTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/court/commonplatform/CommonPlatformCourtEventListenerIntTest.kt
- src/test/resources/application-test.yml
Reverts ministryofjustice/hmpps-person-record#920
tested it on Dev and it does not seem to work as expected
> Revert "Cpr 603 - reworking publishing a large message on a queue"

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/client/model/sqs/messages/Recluster.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/processors/cpr/ReclusterEventProcessor.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/message/CreateUpdateService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/queue/QueueService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/cpr/ReclusterEventListenerIntTest.kt
* Add change record Id do recluster queue to highlight changed record to trigger new recluster process from.
* Let kotlin do UUID encode / decode
> CPR-615 Add changed record to recluster queue message

- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/PersonMatchServiceIntTest.kt
> CPR-616 Add request test

- helm_deploy/hmpps-person-record/values.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/config/SecurityConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/seeding/PopulatePersonMatch.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/seeding/PopulatePersonMatchIntTest.kt
* Going to handle this scenario automatically, in another PR
> Revert "CPR-673 Add ability to upsert single record to person match"

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/CourtMessagePublisher.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/processors/court/AddCprUUID.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/processors/court/CourtEventProcessor.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/processors/prison/PrisonMergeEventProcessor.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/processors/probation/ProbationUnmergeEventProcessor.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/format/EncodingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/message/CreateUpdateService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/message/MergeService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/message/UnmergeService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/court/commonplatform/CommonPlatformCourtEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/court/libra/LibraCourtEventListenerIntTest.kt
> CPR-489 adding cprUUID to topic

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/entity/PersonEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/seeding/UpdateFromProbation.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/message/CreateUpdateService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/message/UnmergeService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/person/PersonKeyService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/person/PersonService.kt
> Rename and reuse

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/api/model/canonical/CanonicalRecord.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/entity/PersonEntity.kt
- src/main/resources/db/migration/V91__rename_sex_to_sex_code.sql
this PR is to only rename the sex col on the person table to sex_code
> CPR-668 rename col sex to sex_code on the person table

- src/main/resources/db/migration/V92__add_constraint_merged_to.sql
add merged to check constraint
> CPR-654-circular-merges

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/api/controller/exceptions/CircularMergeException.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/message/MergeService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/config/MessagingMultiNodeTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/probation/ProbationMergeEventListenerIntTest.kt
create exception for merge scenario
> CPR-654-circular-merge-check

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/entity/PersonEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/jpa/entity/PersonKeyEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/message/NewMergeService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/config/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/probation/ProbationUnmergeEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/NewMergeServiceIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/ReclusterServiceIntTest.kt
* add new merge service to incrementally replace the old one
* No telemetry / event log introduced (yet)
> CPR-610 Add new merge service

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/client/model/match/PersonMatchRecord.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/seeding/PopulatePersonMatchIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/seeding/responses/PersonMatchRequest.kt
* Send source system id
* Use and store source system id on person match
* Then will remove the crn + prison number from transaction
> CPR-669 Send source system ID to person match

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/prison/PrisonEventListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/prison/PrisonMergeEventListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/probation/ProbationDeletionEventListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/probation/ProbationMergeEventListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/processors/probation/ProbationDeleteProcessor.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/queue/SQSListenerService.kt
* Once probation is using all domain events we can utilise these helper funcs better
> CPR-663 Further listener refactor

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/client/PersonMatchClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/health/HealthInfo.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/controller/HealthCheckIntTest.kt
Do not merge until https://github.com/ministryofjustice/hmpps-person-match/pull/262 has gone to production
> CPR-393 simplify healthcheck

- helm_deploy/hmpps-person-record/values.yaml
- helm_deploy/values-dev.yaml
* Enable scaling for extra redundancy
> CPR-79 Enable hpa

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/message/CreateUpdateService.kt
The number of failures to process has gone up a bit too much
> CPR-640 longer delay between retries

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/api/controller/APIController.kt
200 - reinstated to show the missing response example
301 - hidden the content, however, we may need a better desctiption
> fixing the missing example from the swagger page

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/processors/court/CommonPlatformEventProcessor.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/message/listeners/court/commonplatform/CommonPlatformCourtEventListenerIntTest.kt
* this is not logged in current state, widen to capture to see if key is there but value is null or blank
> CPR-755 Widen conditional

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/service/message/CreateUpdateService.kt
try to avoid putting messages back on the queue.
> CPR-640 retry 5 times

- runbooks/003-Rollback.md
add additional steps for checking cluster statuse statistics
> CPR-699-update-runbook-query

- runbooks/003-Rollback.md
* Stats on cluster changes didn't dedup statuses from same cluster
> CPR-699 Update query

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
https://github.com/ministryofjustice/hmpps-helm-charts/blob/9d8ec73918591537330420501e5086bb415fb367/charts/generic-prometheus-alerts/RUNBOOK.md?plain=1#L197
> CPR-790 alert if there is one or more messages on DLQ

- build.gradle.kts
Reverts ministryofjustice/hmpps-person-record#1237
Breaking docker build
> Revert "Update all non major Gradle dependencies"

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/client/model/match/PersonMatchRecord.kt
This is expected to fail until we have modified `hmpps-person-match` to accept masterDefendantId
> CPR-905 send masterDefendantId to hmpps-person-match

- src/main/kotlin/uk/gov/justice/digital/hmpps/personrecord/api/controller/admin/ReclusterController.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/api/controller/admin/ReclusterApiIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/personrecord/test/responses/ResponseSetup.kt
> CPR-922-recluster-nomos-pnc
